openapi: "3.0.2"
info:
  title: Sample API
  version: 1.0.0
servers:
  - url: http://localhost:1000
paths:
  /user:
    get:
      summary: Returns a user.
      operationId: getUser
      responses:
        "200": # status code
          description: A user object
          content:
            application/json:
              schema:
                type: string
